### ISSUE TITLE
Safari UI 

### ISSUE THREAD

**Issue by artroing** [Moving-Castles/eat-drain-arson#10]
![Screenshot 2022-12-01 at 15 49 46](https://user-images.githubusercontent.com/9105714/205103907-347217ff-45ce-4f28-8874-68c82d78d08d.png)

Blur and UI placement issues.

System: Mac
Browser: Safari
Game version: 
https://colorful-clouds.surge.sh/?chainId=4242&worldAddress=0xBB6C9E37E5a0C2A30301680A0fd0dd22c31A10e1&rpc=https://follower.super-degen-chain.lattice.xyz&wsRpc=wss://follower.super-degen-chain.lattice.xyz&initialBlockNumber=13448051&dev=true&snapshot=https://snapshot.simple-infra.lattice.xyz/&stream=https://stream.simple-infra.lattice.xyz/&relay=&faucet=

**Comment by pwrstudio** [comment]
<img width="1440" alt="Screenshot 2022-12-02 at 22 28 43" src="https://user-images.githubusercontent.com/8209990/205390701-324116b8-862a-4b09-83f1-f1670ba49199.png">
